declare module 'gsap/dist/gsap.js';
declare module 'gsap/dist/ScrollTrigger.js';
declare module 'sveltekit-autoimport';
declare const Container: typeof import('$src/components/container.svelte').default;
declare const Section: typeof import('$src/components/section.svelte').default;
declare const Header: typeof import('$src/components/header.svelte').default;
declare const Form: typeof import('$src/components/form.svelte').default;
declare const UiSectionTitle: typeof import('$components/ui/sectionTitle.svelte').default;
declare const UiButton: typeof import('$src/components/ui/button.svelte').default;
declare const UiCtaButton: typeof import('$src/components/ui/ctaButton.svelte').default;
declare const UiH: typeof import('$src/components/ui/h.svelte').default;
declare const UiText: typeof import('$src/components/ui/text.svelte').default;
declare const UiLink: typeof import('$src/components/ui/link.svelte').default;
declare const UiIcon: typeof import('$src/components/ui/icon.svelte').default;
declare const UiCloser: typeof import('$src/components/ui/closer.svelte').default;
declare const UiSpinner: typeof import('$src/components/ui/spinner.svelte').default;
declare const UiBadge: typeof import('$src/components/ui/badge.svelte').default;
declare const UiInput: typeof import('$src/components/ui/input.svelte').default;
declare const UiModal: typeof import('$src/components/ui/modal.svelte').default;
